// <auto-generated />
using System;
using ConcreteDelivery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConcreteDelivery.Data.Migrations
{
    [DbContext(typeof(ConcreteDeliveryDbContext))]
    partial class ConcreteDeliveryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConcreteDelivery.Data.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<int>("DistanceMiles")
                        .HasColumnType("integer")
                        .HasColumnName("distance_miles");

                    b.Property<int?>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int?>("TruckId")
                        .HasColumnType("integer")
                        .HasColumnName("truck_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("PlantId")
                        .HasDatabaseName("idx_orders_plant_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_orders_status");

                    b.HasIndex("TruckId")
                        .HasDatabaseName("idx_orders_truck_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("ConcreteDelivery.Data.Entities.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("plants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643),
                            Name = "North Plant"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643),
                            Name = "South Plant"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643),
                            Name = "East Plant"
                        });
                });

            modelBuilder.Entity("ConcreteDelivery.Data.Entities.PlantInventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ConcreteQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("concrete_quantity");

                    b.Property<int>("GravelQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("gravel_quantity");

                    b.Property<int>("PlantId")
                        .HasColumnType("integer")
                        .HasColumnName("plant_id");

                    b.Property<int>("SandQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sand_quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("PlantId")
                        .IsUnique()
                        .HasDatabaseName("idx_plant_inventory_plant_id");

                    b.ToTable("plant_inventory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcreteQuantity = 500,
                            GravelQuantity = 800,
                            PlantId = 1,
                            SandQuantity = 1000,
                            UpdatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643)
                        },
                        new
                        {
                            Id = 2,
                            ConcreteQuantity = 600,
                            GravelQuantity = 900,
                            PlantId = 2,
                            SandQuantity = 1200,
                            UpdatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643)
                        },
                        new
                        {
                            Id = 3,
                            ConcreteQuantity = 400,
                            GravelQuantity = 700,
                            PlantId = 3,
                            SandQuantity = 800,
                            UpdatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643)
                        });
                });

            modelBuilder.Entity("ConcreteDelivery.Data.Entities.Truck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("driver_name");

                    b.HasKey("Id");

                    b.ToTable("trucks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643),
                            DriverName = "John Smith"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643),
                            DriverName = "Maria Garcia"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643),
                            DriverName = "David Chen"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643),
                            DriverName = "Sarah Johnson"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643),
                            DriverName = "Michael Brown"
                        });
                });

            modelBuilder.Entity("ConcreteDelivery.Data.Entities.TruckStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentOrderId")
                        .HasColumnType("integer")
                        .HasColumnName("current_order_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<int>("TruckId")
                        .HasColumnType("integer")
                        .HasColumnName("truck_id");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("CurrentOrderId");

                    b.HasIndex("Status")
                        .HasDatabaseName("idx_truck_status_status");

                    b.HasIndex("TruckId")
                        .IsUnique()
                        .HasDatabaseName("idx_truck_status_truck_id");

                    b.ToTable("truck_status", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Available",
                            TruckId = 1,
                            UpdatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643)
                        },
                        new
                        {
                            Id = 2,
                            Status = "Available",
                            TruckId = 2,
                            UpdatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643)
                        },
                        new
                        {
                            Id = 3,
                            Status = "Available",
                            TruckId = 3,
                            UpdatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643)
                        },
                        new
                        {
                            Id = 4,
                            Status = "Available",
                            TruckId = 4,
                            UpdatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643)
                        },
                        new
                        {
                            Id = 5,
                            Status = "Available",
                            TruckId = 5,
                            UpdatedAt = new DateTime(2025, 11, 19, 17, 23, 26, 226, DateTimeKind.Utc).AddTicks(2643)
                        });
                });

            modelBuilder.Entity("ConcreteDelivery.Data.Entities.Order", b =>
                {
                    b.HasOne("ConcreteDelivery.Data.Entities.Plant", "Plant")
                        .WithMany("Orders")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConcreteDelivery.Data.Entities.Truck", "Truck")
                        .WithMany("Orders")
                        .HasForeignKey("TruckId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Plant");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("ConcreteDelivery.Data.Entities.PlantInventory", b =>
                {
                    b.HasOne("ConcreteDelivery.Data.Entities.Plant", "Plant")
                        .WithOne("Inventory")
                        .HasForeignKey("ConcreteDelivery.Data.Entities.PlantInventory", "PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plant");
                });

            modelBuilder.Entity("ConcreteDelivery.Data.Entities.TruckStatus", b =>
                {
                    b.HasOne("ConcreteDelivery.Data.Entities.Order", "CurrentOrder")
                        .WithMany()
                        .HasForeignKey("CurrentOrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ConcreteDelivery.Data.Entities.Truck", "Truck")
                        .WithOne("CurrentStatus")
                        .HasForeignKey("ConcreteDelivery.Data.Entities.TruckStatus", "TruckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentOrder");

                    b.Navigation("Truck");
                });

            modelBuilder.Entity("ConcreteDelivery.Data.Entities.Plant", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ConcreteDelivery.Data.Entities.Truck", b =>
                {
                    b.Navigation("CurrentStatus");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
